Solução de Sistemas Lineares

In [13]:
import math
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from scipy.optimize import *

In [14]:
a = np.array([[3,-9],[2,4]])
print(a)

[[ 3 -9]
 [ 2  4]]


In [15]:
b = np.array([[-42],[2]])
print(b)

[[-42]
 [  2]]


In [16]:
z = np.linalg.solve(a,b)
print(z)

[[-5.]
 [ 3.]]


Solução de Sistemas Não-Lineares

In [17]:
def myfunc(z):
    x = z[0]
    y = z[1]
    f = np.empty((2))
    f[0] = pow(x,2)+pow(y,2)-20
    f[1] = y-pow(x,2)
    return f

In [18]:
zGuess = np.array([1,1])
z = fsolve(myfunc,zGuess)
print(z)

[2. 4.]
